'use strict';

// eslint-disable-next-line no-unused-vars
const config = {
  style: 'mapbox://styles/nikplokhov/cl6kgy7jv006114nk3mankaw5',
  accessToken:
    'pk.eyJ1IjoibmlrcGxva2hvdiIsImEiOiJjbDZlc252angxZXA2M2lxbDZ6YTFpaXFuIn0.d33_GQ1uZh7AMMCSI6ZJBg',
  CSV: './nikitapl.csv',
  center: [59.534,60.606],
  zoom: 3.79,
  title: 'GAZPROMNEFT TERMINAL',
  description:
    'Presentation of the company objects.',
  sideBarInfo: ['View_Object', 'Status', 'Object'],
  popupInfo: ['Object'],
  filters: [
    {
      type: 'dropdown',
      title: 'Object: ',
      columnHeader: 'Object',
      listItems: [
        'Laboratory Barabinsk',
        'Laboratory Barnaul',
        'Laboratory Zuevo',
        'Laboratory Gurevsk',
        'Laboratory Paveltsevo',
        'Laboratory Ekaterinburg',
        'Laboratory Ekaterinburg',
        'Laboratory Ivanovo',
        'Laboratory Ishim	',
        'Laboratory Kaluga',
        'Laboratory Kemerovo',
        'Laboratory Kozulka',
        'Laboratory Krasnodar	',
        'Laboratory Krasnoufimsk',
        'Laboratory Krasnoyarsk',
        'Laboratory Moskva',
        'Laboratory Nizhniy Tagil',
        'Laboratory Noyabrsk',
        'Laboratory Novokuznetsk',
        'Laboratory Novosibirsk',
        'Laboratory Novosibirsk',
        'Laboratory Omsk',
        'Laboratory Sankt-Peterburg',
        'Laboratory Serov',
        'Laboratory Tomsk',
        'Laboratory Gladkoe',
        'Laboratory Turinsk',
        'Laboratory Tobolsk',
        'Laboratory Fedorovskaya',
        'Laboratory Chelyabinsk',
        'Artemovskaya',
        'Barabinskaya',
        'Barnaulskaya',
        'Bazhenovskaya',
        'Bolotninskaya',
        'Zuevskaya',
        'Gurevskaya',
        'Dmitrovskaya',
        'Paveltsevskaya',
        'Evsinskaya',
        'Shabrovskaya',
        'Ivanovskaya',
        'Irbitskaya',
        'Isilkulskaya',
        'Ishimskaya',
        'Kaluzhskaya',
        'Kamensk-Uralskaya',
        'Karasukskaya',
        'Kargatskaya',
        'Kemerovskaya',
        'Kineshemskaya',
        'Kozulskaya',
        'Krasnogorskaya',
        'Krasnodarskaya',
        'Krasnoufimskaya',
        'Ordynskaya',
        'Kstovskaya',
        'Mariinskaya',
        'Maslyanskiy tovarnyy park',
        'Nevyanskaya',
        'Noyabrskaya',
        'Novo-Sineglazovskaya',
        'Novokuznetskaya',
        'Novosibirskaya',
        'Omskaya',
        'Kulomzinskaya',
        'Omutinskiy tovarnyy park',
        'Kargapolovskaya',
        'Nizhnetagilskaya',
        'Rybinskaya',
        'Serovskaya',
        'Skalinskaya',
        'Sokurskaya',
        'Fedorovskaya',
        'Tatarskaya',
        'Tobolskaya',
        'Tomskaya',
        'Gladkoe',
        'Talitskaya',
        'Tovarnyy park Turtas',
        'Turinskaya',
        'Chistoozernaya',
        'Chulymskaya',
        'Yalutorovskaya',
      ],
    },
    {
      type: 'checkbox',
      title: 'View Object: ',
      columnHeader: 'View_Object', // Case sensitive - must match spreadsheet entry
      listItems: ['Testing Laboratory', 'Oil base'], // Case sensitive - must match spreadsheet entry; This will take up to six inputs but is best used with a maximum of three;
    },
    {
      type: 'dropdown',
      title: 'Status: ',
      columnHeader: 'Status',
      listItems: [
        'Exploitation',
        'Reconstruction',
        'Conservation',
      ],
    },
  ],
};
